### ISSUE TITLE
Handle all json responses not just code 2xx

### ISSUE THREAD

**Issue by edrik** [toedter/hal-explorer#1]
At least if the response Content-Type is `application/hal+json` or other hal compatible types like `application/vnd.error+json` then it would be nice if the response body was handled regardless of the response code. And in general the response body could still be shown for all `application/*+json` type responses.

**Comment by toedter** [comment]
thx @edrik.

Could you provide me with an example request? 
If I understand you right, HAL Explorer does not handle responses correctly, respectively is not showing the body.

It would be great if you could point me to a running server (that allows CORS) so that I could validate the outputs. Currently I struggle a bit with the Angular HttpClient. For example, HTTP 304 (NOT Modified) is treated as an error...

**Comment by toedter** [comment]
I have made lots of improvements regarding the response body. Please check and re-open if you still have issues.
