### ISSUE TITLE
Please make path adjustable

### ISSUE THREAD

**Issue by ullenboom** [toedter/hal-explorer#54]
Currently, the HAL explorer is under the root path, but this will collide with web applications. Please make the path adjustable via a configuration property like

     spring.data.rest.hal-explorer-base-path=/api

**Comment by toedter** [comment]
Thx for pointing this out.

HAL Explorer itself is just an Angular app and can be deployed anywhere.
If you have a dependency in a Spring Boot application like
`implementation 'org.webjars:hal-explorer:1.1.0'`,
HAL Explorer would be available at http://localhost:8080/webjars/hal-explorer/1.1.0/index.html

But I guess you have a dependency to
`implementation 'org.springframework.data:spring-data-rest-hal-explorer'`

This deployment (including the URL) is then part of the spring-data-rest-hal-explorer project,
see https://github.com/spring-projects/spring-data-rest/tree/main/spring-data-rest-hal-explorer

In this case, please file an issue here: https://github.com/spring-projects/spring-data-rest/issues
Otherwise let me know...
